version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorldStack2021"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v36mbcsgcflp"
s3_prefix = "HelloWorldStack2021"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=167404578292.dkr.ecr.us-east-1.amazonaws.com/helloworldrepo"]
